local utils = require("utils")

local aboutModule = {}

function aboutModule.showAboutScreen(showMainScreen)
  local root = LinearLayout(service)
  root.setOrientation(LinearLayout.VERTICAL)
  root.setBackgroundColor(Color.BLACK)
  root.setPadding(20, 20, 20, 20)

  local scroll = ScrollView(service)
  local layout = LinearLayout(service)
  layout.setOrientation(LinearLayout.VERTICAL)

  local btnBack = Button(service)
  btnBack.setText("Back to Main Menu")
  btnBack.setOnClickListener(View.OnClickListener({
    onClick = function() showMainScreen() end
  }))
  layout.addView(btnBack)

  layout.addView(utils.createHeader("About & User Guide"))

  local infoCreator = TextView(service)
  infoCreator.setText("Created with brilliance and mastery by Moosa Zaib!\nThis powerful extension brings complete GitHub repository and file management right onto your device with absolute speed and convenience.")
  infoCreator.setTextColor(Color.CYAN)
  infoCreator.setTextSize(16)
  infoCreator.setPadding(20, 10, 20, 20)
  layout.addView(infoCreator)

  local btnContact = Button(service)
  btnContact.setText("Contact Moosa Zaib")
  btnContact.setOnClickListener(View.OnClickListener({
    onClick = function()
      pcall(function()
        local intent = Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/923123608972"))
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        service.startActivity(intent)
      end)
      utils.closeExtension()
    end
  }))
  layout.addView(btnContact)

  local guideHeader = TextView(service)
  guideHeader.setText("Step-by-Step Complete Guide:")
  guideHeader.setTextColor(Color.YELLOW)
  guideHeader.setTextSize(18)
  guideHeader.setPadding(20, 30, 20, 10)
  layout.addView(guideHeader)

  local step1 = TextView(service)
  step1.setText("Step 1: Setting Up Your Personal Access Token\nTo use this extension, you must connect it to your GitHub account using a Personal Access Token (PAT). Open 'Set / Edit Personal Access Token' from the main menu. Paste your token (starting with ghp_...) into the text box. Tap 'Save Token'. The app will instantly verify your token with GitHub, display your username and account name upon success, and securely save it for future use.")
  step1.setTextColor(Color.WHITE)
  step1.setTextSize(15)
  step1.setPadding(20, 10, 20, 15)
  layout.addView(step1)

  local step2 = TextView(service)
  step2.setText("Step 2: Viewing & Managing Your GitHub Profile\nTap 'My Profile' on the main menu to inspect your full GitHub account details. Here you can view your username, account type, display name, bio, location, public/private repository counts, starred repositories count, public/private gists, followers count, following count, GitHub plan type, and account creation date.\n\n- Editing Details: You can directly edit your Name, Bio, and Location by tapping their respective Edit buttons.\n\n- Starred Repositories: Tap 'View Starred Repositories' to browse all the repositories you have starred. You can sort them by Name or Date, search through them, and tap any repository to view its files or details.\n\n- Followers & Following: Tap 'View Followers List' or 'View Following List' to inspect who follows you or who you follow. In these lists, you can sort users alphabetically (A-Z or Z-A), search for specific users, and navigate through pages using the Previous and Next Page buttons. Tapping any user's name opens their detailed profile screen.")
  step2.setTextColor(Color.WHITE)
  step2.setTextSize(15)
  step2.setPadding(20, 10, 20, 15)
  layout.addView(step2)

  local step3 = TextView(service)
  step3.setText("Step 3: Viewing, Sorting & Searching Repositories\nOnce your token is saved and verified, tap 'My Repositories' on the main menu to view all your public and private repositories.\n\n- Sorting Options: Tap 'Sort By' to organize your list by Name (A-Z / Z-A), Date (Newest / Oldest), or filter to show Public Only or Private Only.\n\n- Search Feature: Type any repository name in the search bar and tap 'Search' to quickly find a specific repository without scrolling.")
  step3.setTextColor(Color.WHITE)
  step3.setTextSize(15)
  step3.setPadding(20, 10, 20, 15)
  layout.addView(step3)

  local step4 = TextView(service)
  step4.setText("Step 4: Creating a New Repository\nOpen 'My Repositories' from the main menu and tap 'Create New Repository' at the top of the screen.\n\n- Repository Name & Description: Enter your desired repository name in the first text box. Optionally, you can also write a detailed Description in the optional text box below it.\n\n- Visibility Selection: Tap 'Create', then choose whether you want your new repository to be Public or Private. The extension will create it instantly with your provided details.")
  step4.setTextColor(Color.WHITE)
  step4.setTextSize(15)
  step4.setPadding(20, 10, 20, 15)
  layout.addView(step4)

  local step5 = TextView(service)
  step5.setText("Step 5: Browsing, Sorting & Searching Repository Files\nTap on any repository to enter its file browser and inspect all files and folders.\n\n- Sort & Search Files: Tap 'Sort By' to arrange files and folders by Name or Date. Use the search input box to search for any file name inside the current directory.\n\n- File Management: Tap on any file to edit its text content, rename it, copy its raw URL, or delete it. You can navigate through sub-folders seamlessly using the Back button.")
  step5.setTextColor(Color.WHITE)
  step5.setTextSize(15)
  step5.setPadding(20, 10, 20, 15)
  layout.addView(step5)

  local step6 = TextView(service)
  step6.setText("Step 6: Multi-Selection Mode & Bulk Deletion\nTo manage multiple items quickly, press and hold (long-press) on any repository, folder, or file. This instantly enables Selection Mode! You can tap 'Select All' to choose every item on screen or check items individually, then tap 'Delete Selected Repositories' or 'Delete Selected Files' to delete them all in a single bulk operation.")
  step6.setTextColor(Color.WHITE)
  step6.setTextSize(15)
  step6.setPadding(20, 10, 20, 15)
  layout.addView(step6)

  local step7 = TextView(service)
  step7.setText("Step 7: Creating Text Files & Phone Storage Upload\nInside any repository screen, tap 'More Options'. Choose 'Create Text File' to compose a file directly within the app. Or choose 'Upload File From Phone Storage' to browse your phone's internal storage, inspect file sizes, select multiple files (up to 50MB per file limit), and upload them directly to your repository. The app also remembers your last browsed path for convenience.")
  step7.setTextColor(Color.WHITE)
  step7.setTextSize(15)
  step7.setPadding(20, 10, 20, 15)
  layout.addView(step7)

  local step8 = TextView(service)
  step8.setText("Step 8: File Overwrite & Conflict Handling\nWhenever you create or upload a file that already exists in your GitHub repository, the extension automatically prompts you before making changes. You can choose 'Yes, Overwrite' to update the file, or 'Remove from list' / 'Cancel' to skip it safely without replacing your existing data.")
  step8.setTextColor(Color.WHITE)
  step8.setTextSize(15)
  step8.setPadding(20, 10, 20, 15)
  layout.addView(step8)

  local step9 = TextView(service)
  step9.setText("Step 9: Advanced Repository Options (My Repositories)\nInside any of your own repositories, tap 'More Options' to access powerful repository controls:\n\n- Star / Unstar Repository: Tap to easily star or unstar the current repository and see its total star count.\n\n- View & Edit Description: Inspect the current description or tap to update / add a new description for your repository.\n\n- Download Repository: Tap 'Download Repository' to download the entire repository as a ZIP file directly into your phone's Download folder with live progress tracking.\n\n- Links & Settings: Copy direct repository links, copy ZIP download links, rename your repository, switch visibility between Public and Private, or permanently delete the entire repository.")
  step9.setTextColor(Color.WHITE)
  step9.setTextSize(15)
  step9.setPadding(20, 10, 20, 15)
  layout.addView(step9)

  local step10 = TextView(service)
  step10.setText("Step 10: Searching Public Repositories & Users\nTap 'Explore Public Repositories' from the main menu to search across all of GitHub.\n\n- Flexible Searching: Enter any keyword, a specific GitHub username, or a direct repository link (such as owner/repo or full github.com/owner/repo link) into the search box and tap 'Search'.\n\n- Direct Link Parsing: When you paste a direct repository link, the extension automatically detects the owner and repo name, skipping general search to fetch the exact repository directly.")
  step10.setTextColor(Color.WHITE)
  step10.setTextSize(15)
  step10.setPadding(20, 10, 20, 15)
  layout.addView(step10)

  local step11 = TextView(service)
  step11.setText("Step 11: Managing Search History\nYour search queries are stored safely under 'Search History' for instant access:\n\n- Auto-Save Queries: Up to 5 of your most recent search queries are saved automatically on the Public Repositories screen.\n\n- Quick Re-Search: Tap any saved search query button to instantly run that search again without typing.\n\n- Removing History: Tap 'Delete' next to any query to remove it individually, or tap 'Clear All Search History' to wipe your entire search history at once.")
  step11.setTextColor(Color.WHITE)
  step11.setTextSize(15)
  step11.setPadding(20, 10, 20, 15)
  layout.addView(step11)

  local step12 = TextView(service)
  step12.setText("Step 12: Sorting & Navigating Public Search Results\nWhen repository search results appear on screen, you can organize and navigate through them effortlessly:\n\n- Sorting Results: Tap 'Sort By' to arrange search results by Name (A-Z or Z-A) or Date (Date Newest or Date Oldest).\n\n- Pagination: Results are displayed 10 items per page. Tap 'Next Search Result' to view the next page or 'Previous Search Result' to return to previous results.\n\n- Result Details: Each repository item clearly displays its full name, total star count, and short description directly on the list button.")
  step12.setTextColor(Color.WHITE)
  step12.setTextSize(15)
  step12.setPadding(20, 10, 20, 15)
  layout.addView(step12)

  local step13 = TextView(service)
  step13.setText("Step 13: Exploring Public Repository Details & Owner Profiles\nTap any repository in the search results to enter its details screen:\n\n- Owner Details: The owner's username is clearly displayed. Tap 'View [Owner] Profile' to open their detailed account profile screen.\n\n- Description Display: View the complete repository description directly under the owner details.\n\n- Navigation: Use the top 'Back' button or your phone's Back Key to return to the search results or parent directory at any time.")
  step13.setTextColor(Color.WHITE)
  step13.setTextSize(15)
  step13.setPadding(20, 10, 20, 15)
  layout.addView(step13)

  local step14 = TextView(service)
  step14.setText("Step 14: Searching & Sorting Files in Public Repositories\nInside any public repository file browser:\n\n- Folder & File Identifiers: Items are clearly labeled with '[Folder]' or '[File]' for clear accessibility and distinction.\n\n- Searching Files: Type a file name into 'Search files in folder...' and tap 'Search' to instantly filter items in the current directory.\n\n- Sorting Files: Tap 'Sort By' to organize files and folders by Name (A-Z / Z-A) or Date (Newest / Oldest). Folders always remain organized at the top for easy browsing.")
  step14.setTextColor(Color.WHITE)
  step14.setTextSize(15)
  step14.setPadding(20, 10, 20, 15)
  layout.addView(step14)

  local step15 = TextView(service)
  step15.setText("Step 15: Public Repository 'More Options', Downloading & Forking\nInside any public repository screen, tap 'More Options' to access advanced repository tools:\n\n- Star / Unstar Toggle: Live star status and total count are fetched automatically. Tap 'Star Repository' or 'Unstar Repository' to update your star status directly on GitHub (Requires PAT).\n\n- Download Repository: Tap 'Download Repository' to download the full repository as a ZIP file into your phone's Download folder with live progress tracking.\n\n- Copy Links: Easily copy the direct GitHub repository web URL via 'Copy Repo Link' or copy the direct ZIP archive link via 'Copy Zip Link'.\n\n- Fork to My Repositories: Tap 'Fork to My Repositories' to clone and add this public repository directly into your personal GitHub account.")
  step15.setTextColor(Color.WHITE)
  step15.setTextSize(15)
  step15.setPadding(20, 10, 20, 15)
  layout.addView(step15)

  local step16 = TextView(service)
  step16.setText("Step 16: File Code Preview & Download Progress Tracker\nTap on any file inside a public repository to open its view screen:\n\n- Base64 Code Preview: The app fetches and decodes Base64 content into readable UTF-8 text so you can preview code directly on screen.\n\n- Downloading Files: Tap 'Download File' to download the file directly into your phone's Download folder using Android's DownloadManager.\n\n- Live Progress Tracking: A dedicated screen tracks download progress in real-time (percentage or KB loaded).\n\n- Cancellation Dialog: Tap 'Cancel Download' to safely abort an active download with a confirmation prompt.")
  step16.setTextColor(Color.WHITE)
  step16.setTextSize(15)
  step16.setPadding(20, 10, 20, 15)
  layout.addView(step16)

  local step17 = TextView(service)
  step17.setText("Step 17: Public User Profiles & Social Actions\nWhen viewing any public user's profile:\n\n- Comprehensive Profile Information: View username, account type, display name, bio, location, public email, public repos count, gists count, followers, following, and formatted account creation date.\n\n- Follow & Unfollow Actions: Tap 'Follow' or 'Unfollow' to manage social connections directly. The button automatically checks and reflects your live follow status.\n\n- Personal Access Token Check: If you attempt to follow/unfollow without a saved PAT, the extension safely prompts you to save your token first.")
  step17.setTextColor(Color.WHITE)
  step17.setTextSize(15)
  step17.setPadding(20, 10, 20, 15)
  layout.addView(step17)

  local step18 = TextView(service)
  step18.setText("Step 18: Exploring User Followers & Following Networks\nOn any user profile screen:\n\n- Network Lists: Tap 'View Followers List' or 'View Following List' to inspect who follows the user or who the user is following.\n\n- Alphabetical Sorting: Tap 'Sort By' to arrange user lists alphabetically (Name A-Z or Name Z-A).\n\n- User Search: Use 'Search user...' input box to filter users in the list by name.\n\n- Network Pagination: Use 'Previous Page' and 'Next Page' buttons to navigate seamlessly through large user networks (100 users per API page, 10 per local screen).\n\n- Profile Navigation: Tap any user's name in the list to open their complete profile screen instantly.")
  step18.setTextColor(Color.WHITE)
  step18.setTextSize(15)
  step18.setPadding(20, 10, 20, 15)
  layout.addView(step18)

  local step19 = TextView(service)
  step19.setText("Step 19: Easy Navigation & Closing Extension\nYou can press your phone's Back Button at any moment to safely return to the previous menu. To exit, tap 'Close Extension' on the main menu.")
  step19.setTextColor(Color.WHITE)
  step19.setTextSize(15)
  step19.setPadding(20, 10, 20, 15)
  layout.addView(step19)

  local step20 = TextView(service)
  step20.setText("Step 20: Automatic Updates\nWhenever you launch the extension with an active internet connection, it automatically checks for new updates in the background. If an update is found, an update dialog will appear showing the latest changes ('What's New'). Simply tap 'Update Now' to download and install the update automatically, then tap 'Restart Extension' to reload and apply all changes smoothly.")
  step20.setTextColor(Color.WHITE)
  step20.setTextSize(15)
  step20.setPadding(20, 10, 20, 20)
  layout.addView(step20)

  scroll.addView(layout)
  root.addView(scroll)
  utils.enableBackKey(root, function() showMainScreen() end)
  utils.setScreen(root)
end

return aboutModule
